### ISSUE TITLE
Create a Public landing page for new users

### ISSUE THREAD

**Issue by z4hed** [KurooTT/Amazin-soen341project2022#9]
As a Developer, I want to create a public landing page which shows up when a new user visits the website for the first time. 

Epic: A dashboard with a navigation bar containing A list of all items "Categories" - "Account" - "Deals" - "Search bar" - "cart" - "Sign in"

Then below the Nav-bar, display a simple layout of a home page. 

At the bottom of the page display the contact information of the company and links for the features mentioned above.

**Comment by KurooTT** [comment]
Issue solved:  commit directly to the main branch.
